input-dir: [data/factorisation-with-fit,data/factorisation-with-fit-fast-waning,data/factorisation-with-fit-no-waning]
vaccination-policy: [observed,elderly_first,young_first,uniform]
generate-correction-factors: true
save-output: true
samples: 1000
workers: 64